package com.mycompany.sneaksapp.igu.views;

import com.mycompany.sneaksapp.igu.MenuPrincipal;
import com.mycompany.sneaksapp.igu.Work;
import com.mycompany.sneaksapp.igu.WorkInv;
import com.mycompany.sneaksapp.igu.WorkSell;
import com.mycompany.sneaksapp.logica.FrameControllable;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;


public class pnlPrincipal extends javax.swing.JPanel {

    private Work work;
    private WorkInv workInv;
    private WorkSell workSell;

    private FrameControllable currentFrame;
    
    
    public pnlPrincipal(FrameControllable frame) {
        this.currentFrame = frame;
        initComponents();
        InitStyles();
    }
    
    
    private void InitStyles(){
        sbtnGoBack.setSvgImage("back arrow.svg", 40, 37);
        sbtnGoBack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Map<TextAttribute, Object> attributes = new HashMap<TextAttribute, Object>();
        attributes.put(TextAttribute.TRACKING, -0.06);
        lblDashboard.setFont(lblDashboard.getFont().deriveFont(attributes));
        
        Map<TextAttribute, Object> attributes1 = new HashMap<TextAttribute, Object>();
        attributes1.put(TextAttribute.TRACKING, -0.03);
        lblMain1.setFont(lblMain1.getFont().deriveFont(attributes1));
        lblMain2.setFont(lblMain2.getFont().deriveFont(attributes1));
        
        lblSub.setText("<html>This tool will allow you to keep a complete and detailed <br>control of the stock, <u>please click an option.</u></html>");
        lblSub.setForeground(Color.decode("#6c6c6c"));
        lblSub.setFont(lblSub.getFont().deriveFont(attributes));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblMain2 = new javax.swing.JLabel();
        lblMain1 = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        sbtnGoBack = new com.mycompany.sneaksapp.igu.SVGImage();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        lblDashboard.setBackground(new java.awt.Color(0, 0, 0));
        lblDashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(0, 0, 0));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDashboard.setText("Dashboard");

        lblMain2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        lblMain2.setText("efficiently and optimally.");

        lblMain1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        lblMain1.setText("Manage your franchise ");

        lblSub.setBackground(new java.awt.Color(255, 255, 255));
        lblSub.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblSub.setText("This tool will allow you to keep a complete and detailed  control of the stock, please click an option.");
        lblSub.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        sbtnGoBack.setText("sVGImage2");
        sbtnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbtnGoBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sbtnGoBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sbtnGoBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sbtnGoBackMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSub, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbtnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblDashboard))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(sbtnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(179, 179, 179)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lblMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(lblSub, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sbtnGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbtnGoBackMouseClicked
        sbtnGoBack.setSvgImage("clkBackArrow.svg", sbtnGoBack.getWidth(), sbtnGoBack.getHeight());
        if (this.currentFrame != null) {
            this.currentFrame.closeFrame();
        }
        MenuPrincipal back = new MenuPrincipal();
        back.setVisible(true);
        back.setLocationRelativeTo(null);
    }//GEN-LAST:event_sbtnGoBackMouseClicked

    private void sbtnGoBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbtnGoBackMouseEntered
        sbtnGoBack.setSvgImage("hvrBackArrow.svg", sbtnGoBack.getWidth(), sbtnGoBack.getHeight());
    }//GEN-LAST:event_sbtnGoBackMouseEntered

    private void sbtnGoBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbtnGoBackMouseExited
        sbtnGoBack.setSvgImage("back arrow.svg", sbtnGoBack.getWidth(), sbtnGoBack.getHeight());
    }//GEN-LAST:event_sbtnGoBackMouseExited

    private void sbtnGoBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbtnGoBackMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbtnGoBackMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblMain1;
    private javax.swing.JLabel lblMain2;
    private javax.swing.JLabel lblSub;
    private com.mycompany.sneaksapp.igu.SVGImage sbtnGoBack;
    // End of variables declaration//GEN-END:variables
    
    public void setWork(Work work) {
    this.work = work;
    }

    public void setWorkInv(WorkInv workInv) {
        this.workInv = workInv;
    }
    
    public void setWorkSell(WorkSell workSell) {
        this.workSell = workSell;
    }

}
